
package wsdl_agence;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OffresAggregeesServiceImplService", targetNamespace = "http://services/", wsdlLocation = "http://localhost:3000/offreservice?wsdl")
public class OffresAggregeesServiceImplService
    extends Service
{

    private final static URL OFFRESAGGREGEESSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException OFFRESAGGREGEESSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName OFFRESAGGREGEESSERVICEIMPLSERVICE_QNAME = new QName("http://services/", "OffresAggregeesServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3000/offreservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OFFRESAGGREGEESSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        OFFRESAGGREGEESSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public OffresAggregeesServiceImplService() {
        super(__getWsdlLocation(), OFFRESAGGREGEESSERVICEIMPLSERVICE_QNAME);
    }

    public OffresAggregeesServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OFFRESAGGREGEESSERVICEIMPLSERVICE_QNAME, features);
    }

    public OffresAggregeesServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, OFFRESAGGREGEESSERVICEIMPLSERVICE_QNAME);
    }

    public OffresAggregeesServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OFFRESAGGREGEESSERVICEIMPLSERVICE_QNAME, features);
    }

    public OffresAggregeesServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OffresAggregeesServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OffresAggregeesService
     */
    @WebEndpoint(name = "OffresAggregeesServiceImplPort")
    public OffresAggregeesService getOffresAggregeesServiceImplPort() {
        return super.getPort(new QName("http://services/", "OffresAggregeesServiceImplPort"), OffresAggregeesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OffresAggregeesService
     */
    @WebEndpoint(name = "OffresAggregeesServiceImplPort")
    public OffresAggregeesService getOffresAggregeesServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "OffresAggregeesServiceImplPort"), OffresAggregeesService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OFFRESAGGREGEESSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw OFFRESAGGREGEESSERVICEIMPLSERVICE_EXCEPTION;
        }
        return OFFRESAGGREGEESSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
