
package wsdl_hotel;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelService", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<wsdl_hotel.Offre>
     * @throws ParseException_Exception
     * @throws WrongLoginException_Exception
     * @throws WrongDateException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOffres", targetNamespace = "http://services/", className = "wsdl_hotel.GetOffres")
    @ResponseWrapper(localName = "getOffresResponse", targetNamespace = "http://services/", className = "wsdl_hotel.GetOffresResponse")
    @Action(input = "http://services/HotelService/getOffresRequest", output = "http://services/HotelService/getOffresResponse", fault = {
        @FaultAction(className = WrongDateException_Exception.class, value = "http://services/HotelService/getOffres/Fault/WrongDateException"),
        @FaultAction(className = WrongLoginException_Exception.class, value = "http://services/HotelService/getOffres/Fault/WrongLoginException"),
        @FaultAction(className = ParseException_Exception.class, value = "http://services/HotelService/getOffres/Fault/ParseException")
    })
    public List<Offre> getOffres(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4)
        throws ParseException_Exception, WrongDateException_Exception, WrongLoginException_Exception
    ;

    /**
     * 
     * @return
     *     returns wsdl_hotel.Hotel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHotel", targetNamespace = "http://services/", className = "wsdl_hotel.GetHotel")
    @ResponseWrapper(localName = "getHotelResponse", targetNamespace = "http://services/", className = "wsdl_hotel.GetHotelResponse")
    @Action(input = "http://services/HotelService/getHotelRequest", output = "http://services/HotelService/getHotelResponse")
    public Hotel getHotel();

}
